'use client'

import { useState, useEffect } from 'react';
import { Database, RefreshCw, TrendingUp, Loader2 } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';

interface Stats {
  locations: number;
  shifts: number;
  moments: number;
  executions: number;
}

export default function RobotIntelligencePage() {
  const { getIdToken } = useAuth();
  const [syncing, setSyncing] = useState(false);
  const [stats, setStats] = useState<Stats | null>(null);
  const [loading, setLoading] = useState(true);
  
  useEffect(() => {
    loadStats();
  }, []);
  
  async function loadStats() {
    try {
      const token = await getIdToken();
      const response = await fetch('/api/admin/robot-intelligence/stats', {
        headers: {
          'Authorization': `Bearer ${token}`,
        },
      });
      
      if (response.ok) {
        const data = await response.json();
        setStats(data);
      }
    } catch (error) {
      console.error('Failed to load stats:', error);
    } finally {
      setLoading(false);
    }
  }
  
  async function syncData() {
    setSyncing(true);
    try {
      const token = await getIdToken();
      const response = await fetch('/api/admin/sync', { 
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
        },
      });
      
      const data = await response.json();
      if (data.success) {
        alert(`Data synced successfully!\n\nLocations: ${data.stats?.locations || 0}\nTasks: ${data.stats?.tasks || 0}\nShifts: ${data.stats?.shifts || 0}`);
        loadStats();
      } else {
        alert('Sync failed: ' + (data.error || 'Unknown error'));
      }
    } catch (error) {
      console.error('Sync failed:', error);
      alert('Sync failed. Check console for details.');
    } finally {
      setSyncing(false);
    }
  }
  
  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loader2 className="h-8 w-8 animate-spin text-gray-600" />
      </div>
    );
  }
  
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Robot Intelligence Database
          </h1>
          <p className="text-gray-600">
            SQL-based visual job database for robot learning. Completely separate from the teleop portal.
          </p>
        </div>
        
        <button
          onClick={syncData}
          disabled={syncing}
          className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
        >
          <RefreshCw className={`h-4 w-4 ${syncing ? 'animate-spin' : ''}`} />
          {syncing ? 'Syncing...' : 'Sync from Firestore'}
        </button>
      </div>
      
      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <StatCard
          label="Locations Synced"
          value={stats?.locations || 0}
          icon={Database}
        />
        <StatCard
          label="Shifts Recorded"
          value={stats?.shifts || 0}
          icon={Database}
        />
        <StatCard
          label="Moments Created"
          value={stats?.moments || 0}
          icon={Database}
        />
        <StatCard
          label="Robot Executions"
          value={stats?.executions || 0}
          icon={TrendingUp}
        />
      </div>
      
      {/* Info Section */}
      <div className="bg-white border border-gray-200 rounded-lg p-6">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">About Robot Intelligence</h2>
        <div className="space-y-3 text-sm text-gray-600">
          <p>
            This database is <strong>completely separate</strong> from the teleop portal. It syncs data one-way from Firestore to PostgreSQL for robot-specific queries and learning.
          </p>
          <p>
            <strong>Moments</strong> are atomic units of robot-executable work. They can be created manually, extracted from task instructions, or generated by AI from video.
          </p>
          <p>
            <strong>Media</strong> (videos, images) can be linked to moments to provide visual context for robot execution.
          </p>
          <p>
            <strong>Location Preferences</strong> allow customizing moments for specific locations (e.g., &quot;This kitchen uses a different cleaning product&quot;).
          </p>
        </div>
      </div>
      
      {/* Tabs Placeholder */}
      <div className="bg-white border border-gray-200 rounded-lg">
        <div className="border-b border-gray-200 p-4">
          <div className="flex gap-2">
            <button className="px-4 py-2 bg-blue-100 text-blue-600 rounded-lg font-medium">
              Moments
            </button>
            <button className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg">
              Media
            </button>
            <button className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg">
              Preferences
            </button>
            <button className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg">
              Analytics
            </button>
          </div>
        </div>
        
        <div className="p-6">
          <p className="text-gray-600 text-center py-12">
            Select a tab to view data. Coming soon: Moment creation, media upload, and analytics.
          </p>
        </div>
      </div>
    </div>
  );
}

function StatCard({ label, value, icon: Icon }: { label: string; value: number; icon: any }) {
  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6">
      <div className="flex items-center gap-3 mb-2">
        <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
          <Icon className="h-5 w-5 text-blue-600" />
        </div>
        <span className="text-sm text-gray-600">{label}</span>
      </div>
      <div className="text-2xl font-bold text-gray-900">{value}</div>
    </div>
  );
}

